
VERSION = 0.1.0
MAIN_FILE = Smooth.cpp
FLAGS = -g3 -std=c++20 -I src
CPP_FILES = src\TOML\\*.cpp src\util\\*.cpp src\PreTokenizer\\*.cpp src\Tokenizer\\*.cpp src\Literal\\*.cpp src\Parser\\*.cpp

build:
	copy src\$(MAIN_FILE) generated\$(MAIN_FILE)
	powershell -Command "(gc generated\$(MAIN_FILE)) -replace '{version}', '$(VERSION)' | Out-File -encoding ASCII generated\$(MAIN_FILE)"
	g++ generated\$(MAIN_FILE) $(FLAGS) $(CPP_FILES) -o test\smooth.exe

run: build
	cd test && smooth.exe && cd ..

legacyBuild:
	g++ -g3 -std=c++20 legacy\src\smooth.cpp -o legacy\test\smooth.exe
