
VERSION = 0.7.0
MAIN_FILE = Smooth.cpp
FLAGS = -g3 -std=c++20 -I src
CPP_FILES = src\util\\*.cpp src\PreTokenizer\\*.cpp src\Tokenizer\\*.cpp src\Literal\\*.cpp src\Parser\\*.cpp

default: build

preprocess:
	copy src\$(MAIN_FILE) generated\$(MAIN_FILE)
	powershell -Command "(gc generated\$(MAIN_FILE)) -replace '{version}', '$(VERSION)' | Out-File -encoding ASCII generated\$(MAIN_FILE)"

build: preprocess
	g++ generated\$(MAIN_FILE) $(FLAGS) $(CPP_FILES) -o test\smooth.exe

run: build
	cd test && smooth.exe Prova.smt && cd ..

legacyBuild:
	g++ -g3 -std=c++20 legacy\src\smooth.cpp -o legacy\test\smooth.exe
